# Generated by Django 5.1.1 on 2024-10-08 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_actividadextracurricular_horarioactividad_ramo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio_en_dia', models.BooleanField(default=True)),
                ('tiempo_llegada_uni', models.IntegerField(default=0)),
                ('tiempo_preparacion', models.IntegerField(default=0)),
                ('lugar_estudio', models.CharField(choices=[('casa', 'Casa'), ('uni', 'Universidad')], max_length=50)),
                ('preferencias_personalizadas', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
