# Generated by Django 5.1.1 on 2024-10-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_preferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencia',
            name='estudio_en_dia',
        ),
        migrations.AddField(
            model_name='preferencia',
            name='horario_estudio',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='Tarde', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencia',
            name='tiempo_antes_dormir',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='lugar_estudio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
