# Generated by Django 5.1.1 on 2024-10-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0005_calendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='miApp.calendario')),
            ],
        ),
    ]
